variable "location" {}
variable "resource-group-name" {}
variable "network-interface-id" {}
variable "environment" {}
variable "image-storage-account-id" {}
variable "subnet-id" {}
variable "security-group-id" {}
variable "network-interface-name" {}
variable "dockertoken" {}
variable "tls-private-key-pem" {}
variable "public_key_openssh" {}
