name: "Master: Build - Push dev Version to Docker Hub"
on:
    push:
      branches: 
        - master
jobs:
    database_build:
      runs-on: ubuntu-latest
      name: Docker Container vorbereiten und ins Docker Repository pushen
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
        - name: Login to DockerHub
          run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
        - name: Build Docker image
          run: docker build --build-arg password=${{secrets.DATABASE_PASSWORD}} ./ --tag onnythunder/feedibus-master:latest
        - name: Push to DockerHub
          run: docker push onnythunder/feedibus-master:latest